#!/bin/bash

# Copyright (c) The Monero Project
# 
# This source code is licensed under the BSD-3 license found in the
# LICENSE file in the root directory of this source tree.
# 
# 
# Parts of this file are originally copyright (c) 2012-2013 The Cryptonote developers

case $1 in
   config)
        cat <<'EOM'
graph_title Height
graph_vlabel height
graph_category monero
height.label height
height.type COUNTER
EOM
        exit 0;;
esac

printf "height.value "
# rewrite using curl or similar: /home/user/bitmonero/build/release/src/connectivity_tool --ip=127.0.0.1 --rpc_port=8081 --timeout=1000 --rpc_get_daemon_info | grep height | cut -d ' ' -f2
