#!/bin/bash

# Copyright (c) The Monero Project
# 
# This source code is licensed under the BSD-3 license found in the
# LICENSE file in the root directory of this source tree.
# 
# 
# Parts of this file are originally copyright (c) 2012-2013 The Cryptonote developers

case $1 in
   config)
        cat <<'EOM'
graph_title tx_pool_size
graph_vlabel tx_pool_size
graph_category monero
tx_pool_size.label tx_pool_size
EOM
        exit 0;;
esac

printf "tx_pool_size.value "
# rewrite using curl or similar: /home/user/bitmonero/build/release/src/connectivity_tool --ip=127.0.0.1 --rpc_port=8081 --timeout=1000 --rpc_get_daemon_info | grep tx_pool_size| cut -d ' ' -f2
