name: ci/gh-actions/gitian

on:
  push:

jobs:
  build-gitian:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - name: "Linux"
            option: "l"
          - name: "Windows"
            option: "w"
          - name: "Android"
            option: "a"
          - name: "FreeBSD"
            option: "f"
          - name: "macOS"
            option: "m"
    name: ${{ matrix.operating-system.name }}
    steps:
    - name: prepare gitian build host 
      run: |
        sudo usermod -aG docker $USER
    - name: build
      run: |
        branch="master"
        curl -O https://raw.githubusercontent.com/monero-project/monero/${branch}/contrib/gitian/gitian-build.py
        sudo chmod +x gitian-build.py
        cat gitian-build.py
        ls -la
        sudo ./gitian-build.py --setup --docker github-actions ${branch}
        sudo ./gitian-build.py --docker --detach-sign --no-commit --build -j 3 -o ${{ matrix.operating-system.option }} github-actions ${master}
    - name: post build
      run: |
        shasum -a256 out/${{ github.ref_name }}/*
        echo \`\`\` >> $GITHUB_STEP_SUMMARY
        shasum -a256 out/${{ github.ref_name }}/* >> $GITHUB_STEP_SUMMARY
        echo \`\`\` >> $GITHUB_STEP_SUMMARY
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ matrix.operating-system.name }}
        path: |
          out/${{ github.ref_name }}/*
